### ISSUE TITLE
網站的提交issue連結掛掉了

### ISSUE THREAD

**Issue by adsa562** [jiajiaxd/VoteReboot#2]
在mcbbs路過看到您的作品，剛好發現下載位址中，
https://open.jiajiaxd.top/vr/ 網站內「点击此处反馈BUG」連結，
> https://github.com/jiajiaxd/VRissues/issues

應修正為

> https://github.com/jiajiaxd/VoteReboot/issues

**Comment by jiajiaxd** [comment]
已经修复
