### ISSUE TITLE
小概率时投票时玩家退出服务器造成投票数量大于重启数量

### ISSUE THREAD

**Issue by GaoXanSheng** [jiajiaxd/VoteReboot#3]
if (!getCS("checkplayer").equals("true"))
                    sendGlobalMessage("§e" + PlayerName + " §a进行了投票 本服共§e" + OnlinePlayers + "§a人在线，共需要§e" + getNeedPlayers() + "§a人投票 目前票数：§e" + (real + 1));
                else
                    sendGlobalMessage("§e" + PlayerName + " §a进行了投票 本服共§e" + OnlinePlayers + "§a人在线，共需要§e" + getNeedPlayers() + "§a人投票（不包含正在挂机的玩家） 目前票数：§e" + (real + 1));
            }
        }
        if (real + 1 == getNeedPlayers()||real + 1 < getNeedPlayers()) {
            sendGlobalMessage("投票已经完成！服务器将在十秒后重启！");
            isVoting = false;
            isRebooting = 

> true;

**Comment by jiajiaxd** [comment]
请详细描述一下问题

**Comment by GaoXanSheng** [comment]
当多个玩家在线时，如果有玩家退出，需要投票数量不等于实际数量，上面已给解决方案
